### ISSUE TITLE
Requesting an icon which does not exist returns IconData Object not null

### ISSUE THREAD

**Issue by ride4sun** [flutter-studio/flutter-icons#12]
If I request an Icon which does not exist IconData gets returned anyway with the codePoint = null. This leads to a weird flutter assert which has nothing to do with the IconData and it is hard to track.
Could u please just return null or throw an exception

 IconData data = MaterialIcons.getIconData(key);

**Comment by 2534290808** [comment]
Assertions have been added to the getIconData method

**Comment by 2534290808** [comment]
The 1.0.0 release refactored the API

**Comment by ride4sun** [comment]
It would be nice if you could indicate the new behavior here...

**Comment by ride4sun** [comment]
Just updated and it seems like there are only static accessors to replace getIconData(String) is gone. Is there a replacement? This is breaking all my late binding code where icons are defined by strings.
The probably fixes the tree-shaking but breaks late-binding

**Comment by mateusfccp** [comment]
@ride4sun 

I also would like to know. There are places on my source where the IconData is dinamically obtained with `FontAwesome.getIconData(somevarwithiconname)`. Is there a way to do something similar to this in this new API?

**Comment by 2534290808** [comment]
> Just updated and it seems like there are only static accessors to replace getIconData(String) is gone. Is there a replacement? This is breaking all my late binding code where icons are defined by strings.
> The probably fixes the tree-shaking but breaks late-binding

Please use the previous version 1.0.0

**Comment by ride4sun** [comment]
@2534290808 This does not give any `new` Icon updates - right?
