### ISSUE TITLE
All Icons should be searchable in one list - copy and paste should work to get the names

### ISSUE THREAD

**Issue by ride4sun** [flutter-studio/flutter-icons#13]
All Icons should be searchable in one list to search all libraries - copy and paste should work to get the names to copy them. Also, the search icon has to be clicked to start a search. Search should be triggered by just typing. The Chinese string in the search field does not work with most of the world. Could you change it to English to make it more comprehensible ( I am German ) ?

I like the package - don't get me wrong.

**Comment by 2534290808** [comment]
Thank you for your issue. I will amend it

**Comment by 2534290808** [comment]
The 1.0.0 release refactored the API

**Comment by ride4sun** [comment]
Any pointers what the new behavior is. Would be good for newcomers as well
