### ISSUE TITLE
Access all icons with single API

### ISSUE THREAD

**Issue by deadsoul44** [flutter-studio/flutter-icons#25]
Is it possible to access all icons with a single API? For example, I want to select the best looking calendar icon from all of the sets. But, I have to type the name of all sets one by one and add dot calendar after them. If all the icons are accessible from a single class it would be easier to select the best calendar icon. 

Thank you for the great package.

**Comment by 2534290808** [comment]
If two sets have the same Icon name, using a single API can cause a conflict

**Comment by deadsoul44** [comment]
If there are same icon names, the name of the icon set can be appended.

**Comment by 2534290808** [comment]
That's a good idea

**Comment by 2534290808** [comment]
The new version adds the FlutterIcons class to access all icons
