### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by adarsh-technocrat** [flutter-studio/flutter-icons#41]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by rgr** [comment]
Any news ?

**Comment by adarsh-technocrat** [comment]
> Any news ?

yup! there is an attached PR that will resolve this issue :)

**Comment by rgr** [comment]
Great news ! Thanks @adarsh-technocrat. Hope it gets accepted soon!

**Comment by rgr** [comment]
@2534290808 could you accept the null safety PR please?

**Comment by joaovvrodrigues** [comment]
@adarsh-technocrat how add this in my project ?

 flutter_icons: 
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons/tree/null-safety-migration

don't work here, Could you upload your changes to your project's main?

**Comment by adarsh-technocrat** [comment]
> flutter_icons

Hey, @joaovvrodrigues I would prefer you to make a different branch for your null safety version!
here I will change the base branch to that null safety branch and then you can merge it =)

**Comment by rgr** [comment]
@adarsh-technocrat while waiting for your PR to be accepted did you succeed in importing your own branch into your project ? How do you do that ?

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat while waiting for your PR to be accepted did you succeed in importing your own branch into your project ? How do you do that ?

Sorry @LearningRaph I could not get you  but as far as I could understand I just went through the series of steps for migrating this sample and package :-

1. Forked the official  repo
2. Cloned the forked repo to my local machine
3. Created the different branch for the null safety migration  eg here :-  `git branch  null-safety-migration`
4. Applied Migration  in the  `null-safety-migration`  branch
5. Committed the changes 
6. Pushed the branch to my forked repo
7. Finally Generated the PR.
 
 Im not Sure @LearningRaph  is this is the right Answer for your Question!

**Comment by rgr** [comment]
Nope :) I was wondering if you could use your fork in your flutter app. If we don't have news from the creator it would be a good option...

**Comment by adarsh-technocrat** [comment]
Ahh.. no @LearningRaph  until and unless it is Publish to the pub. div I think we cannot use the null-safety version of this package :)

**Comment by joaovvrodrigues** [comment]
@adarsh-technocrat @LearningRaph 
in fact you can, and that's what I'm trying to say,
If you move your changes to the project's Branch Master, you can use the package directly from git.

`flutter_icons:`
  `    git:`
`      url: https://github.com/adarsh-technocrat/flutter-icons`

![Captura de Tela 2021-03-06 às 14 47 04](https://user-images.githubusercontent.com/31359621/110215943-20285480-7e8b-11eb-961f-a214af39e2e7.png)

because you created a new branch, then we can't access it, it needs to be on the master, as far as I know.

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat @LearningRaph
> in fact you can, and that's what I'm trying to say,
> If you move your changes to the project's Branch Master, you can use the package directly from git.
> 
> `flutter_icons:`
> ` git:`
> ` url: https://github.com/adarsh-technocrat/flutter-icons`
> 
> ![Captura de Tela 2021-03-06 às 14 47 04](https://user-images.githubusercontent.com/31359621/110215943-20285480-7e8b-11eb-961f-a214af39e2e7.png)
> 
> because you created a new branch, then we can't access it, it needs to be on the master, as far as I know.

oooh got it @joaovvrodrigues  thanks  I'll do the changes right now =)

**Comment by adarsh-technocrat** [comment]
Hey, @joaovvrodrigues I merged the null-safety-migration branch to the master branch see now if you can access the null safety version!

**Comment by joaovvrodrigues** [comment]
It worked just fine! 🥇

**Comment by rgr** [comment]
Works for me too ! Great team work :)

**Comment by ghost** [comment]
As an info
```
some_package:
  git:
    url: blabla
    ref: some_branch
```
works to use a certain branch of a project instead of master

**Comment by aytunch** [comment]
@flutter-studio or @2534290808 Are you planning on accepting  @adarsh-technocrat 's Null-safety PR? Also are you planning on maintaining this package? Or are you considering accepting new maintainers?

**Comment by eric-taix** [comment]
Until this PR has been merged to master and the package has been published to `pub.dev`, you can update your pubspec.yaml to:
```
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
```

**Comment by davidAg9** [comment]
any one tried to contact this package owner
...it will be great If they left a number /email or WhatsApp so we can contact them...it seem this and other packages I have used in my app are tending towards the possibility of  being abandoned or not maintain or worse discontinued

**Comment by davidAg9** [comment]
> Until this PR has been merged to master and the package has been published to `pub.dev`, you can update your pubspec.yaml to:
> 
> ```
>   flutter_icons:
>     git:
>       url: https://github.com/adarsh-technocrat/flutter-icons.git
>       branch: null-safety-migration
> ```

your package need null safety support too (fluid bottom nav bar)

**Comment by aytunch** [comment]
It is April, will this package be maintained in the future? We are depending on it a lot. If not, we will try to migrate to another solution unfortunately :/

**Comment by joaovvrodrigues** [comment]
@aytunch I agree with you, I believe that I will take the same action. There are similar packages that have already been migrated and are constantly being updated. Last update of the package was in June 2020.

**Comment by aytunch** [comment]
> @aytunch I agree with you, I believe that I will take the same action. There are similar packages that have already been migrated and are constantly being updated. Last update of the package was in June 2020.

@joaovvrodrigues i hear you. Would you please share some of the alternatives which are being maintained and support null-safety so others can benefit as well

**Comment by joaovvrodrigues** [comment]
I believe that this package here will meet this need: https://pub.dev/packages/fluttericon 

I think I will already start the migration progress in my app. It may not have exactly the same icons, but it always gets one that can be replaced by something similar.

**Comment by ydang204** [comment]
Any news? I am waiting for this part too!

**Comment by deadsoul44** [comment]
Any update?

**Comment by CodeQuestK** [comment]
Any updates on migration to null safety?

**Comment by fernando-s97** [comment]
Any updates?

**Comment by joaovvrodrigues** [comment]
@2534290808 , please merge this.

**Comment by mrripp3r** [comment]
Any news on migration to null safety?

**Comment by hanyska** [comment]
+1

**Comment by diegopq** [comment]
@udiedrichsen  any news?

**Comment by fernando-s97** [comment]
Why was it closed?

**Comment by giorgio79** [comment]
https://pub.dev/packages/flutter_vector_icons
PS This package looks like needs an IconButton, instead of the simple Icon

**Comment by nehal076** [comment]
Any update ? Update to null safety.

**Comment by aytunch** [comment]
@adarsh-technocrat I am using your fork after null-safety but there is a dependency issue as you can see below.

> Because flutter_native_splash >=1.1.9 depends on args ^2.1.1 and flutter_launcher_icons 0.9.0 depends on args 2.0.0, flutter_native_splash >=1.1.9 is incompatible with flutter_launcher_icons 0.9.0.
> 
> And because no versions of flutter_launcher_icons match >0.9.0 <0.10.0, flutter_native_splash >=1.1.9 is incompatible with flutter_launcher_icons ^0.9.0.
> So, because bare_bones depends on both flutter_launcher_icons ^0.9.0 and flutter_native_splash ^1.2.0, version solving failed.
> 
> pub get failed (1; So, because bare_bones depends on both flutter_launcher_icons ^0.9.0 and flutter_native_splash ^1.2.0, version solving failed.)
> exit code 1

**Comment by luohao123** [comment]
Deprecate this lib , avvoid using it any longer, I have removed all icons from this lib, using FluentIcons instead.
