### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by baimamboukar** [flutter-studio/flutter-icons#46]
Getting errors related to null safety support
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:flutter_icons

For solutions, see https://dart.dev/go/unsound-null-safety

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:flutter_icons

**Please do migrate the package to null safety **

**Comment by amirhsn** [comment]
As per July 2020, Flutter use a null safety sound to prevent variables to be assign with the null values. From your issues, the only way to fix the error is 

Downgrade the package version by simply check the version that has no null safety support on it

OR

disable the null safety by simply change the SDK Enviroment on `pubspec.yaml` files to support from SDK level 2.7.0

`sdk: ">=2.7.0 <3.0.0"`

**Comment by nehal076** [comment]
+1000

**Comment by baimamboukar** [comment]
> +1000

???

**Comment by nehal076** [comment]
I agree with this issue. Please upgrade the package to null safety.

**Comment by jibiel** [comment]
Made the PR that addresses the problem: https://github.com/flutter-studio/flutter-icons/pull/47.
