### ISSUE TITLE
Outline or solid is not quit clear

### ISSUE THREAD

**Issue by lucasjinreal** [flutter-studio/flutter-icons#8]
Hi, thanks for wonderful icons!

the icon preview from website, is not same with I set in flutter app:

<img width="66" alt="image" src="https://user-images.githubusercontent.com/21303438/64835479-bf62e780-d618-11e9-9146-f718f79844a2.png">

As you can see, the grin icon it not solid, while website is like this:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/21303438/64835491-d1dd2100-d618-11e9-8929-d307e6650bbb.png">

I want it to be solid so that fits the style of my app. Do u know why it's not same?

**Comment by 2534290808** [comment]
Which Icon library is it ？

**Comment by lucasjinreal** [comment]
I knew it should set weights as SLOID now.
