### ISSUE TITLE
Does cherry picking work with this library

### ISSUE THREAD

**Issue by ride4sun** [flutter-studio/flutter-icons#9]
I am wondering if by using this Library dart/ flutter tree shaking still works or if all Icons are loaded in memory because I can access them with an indexer (map)?

FYI
Tree shaking. In computing, tree shaking is a dead code elimination technique that is applied when optimizing code written in ECMAScript dialects like Dart, JavaScript, or TypeScript into a single bundle that is loaded by a web browser.

**Comment by ride4sun** [comment]
Filed a stackoverflow question:
https://stackoverflow.com/questions/59507591/how-can-i-make-icon-loading-work-with-late-binding-and-tree-shaking-in-flutter-a

**Comment by 2534290808** [comment]
Now you can use the `split_icon` command to reduce the package size,see #23
